GET http://localhost:3000/
###

//-----------------------------------------------------

// GET ALL todos API (1)
GET http://localhost:3000/todos/
###

// Scenario 1 API (1)
GET http://localhost:3000/todos/?status=TO%20DO
###

// Scenario 2 API (1)
GET http://localhost:3000/todos/?priority=HIGH
###

// Scenario 3 API (1)
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
###

// Scenario 4 API (1)
GET http://localhost:3000/todos/?search_q=Buy
###

// Scenario 5 API (1)
GET http://localhost:3000/todos/?category=WORK&status=DONE
###

// Scenario 6 API (1)
GET http://localhost:3000/todos/?category=HOME
###

// Scenario 7 API (1)
GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH
###



//-----------------------------------------------------

// GET todo by id API (2)
GET http://localhost:3000/todos/2/
###

//-----------------------------------------------------

// GET list of todos by dueDate query API (3)
GET http://localhost:3000/agenda/?date=2021-4-04
###

//-----------------------------------------------------

// ADD todo API (4)
POST http://localhost:3000/todos/
Content-Type: application/json 

{
  "id": 6,
  "todo": "Go to Market",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}
###

//-----------------------------------------------------

// UPDATE todo by id API (5)
PUT http://localhost:3000/todos/6/
Content-Type: application/json 
// **Scenario 1**

# {
#  "status": "DONE"
# }

// **Scenario 2**

# {
#  "priority": "HIGH"
# }

// **Scenario 3**

{
 "todo": "Kill to maneesha"
}

// **Scenario 4**

# {
#  "category": "LEARNING"
# }

// **Scenario 5**

# {
#  "dueDate": "2023-3-26"
# }

###

//-----------------------------------------------------

//DELETE todo by id API (6)
DELETE http://localhost:3000/todos/6/
###


